"""create channelmembers table

Revision ID: 9b622ac1b1cb
Revises: 0d0c3247656c
Create Date: 2024-05-29 19:25:24.546768

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '9b622ac1b1cb'
down_revision = '0d0c3247656c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_memberships',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
    sa.Column('channel_id', sa.Integer(), sa.ForeignKey('channels.id'), nullable=False),
    sa.Column('created_at', sa.DateTime()),
    sa.Column('updated_at', sa.DateTime())
    )


    if environment == "production":
        op.execute(f"ALTER TABLE channel_memberships SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_memberships')
    # ### end Alembic commands ###
